Signup
PyPila/apof pull request #5
Opened 2017-01-31 11:22 UTC by RadekLejba

2017-01-31 11:38 UTC, KamiNoSierhej commented on src/portal/templates/portal/base.html
> +    <meta charset="utf-8">
Indentation

2017-01-31 11:39 UTC, KamiNoSierhej commented on src/portal/templates/portal/base.html
> +    <div id="content-wrapper">
same

2017-01-31 11:43 UTC, KamiNoSierhej commented on src/portal/urls.py
> +    url(r'^login/$',
url(
    some stuff,
    other things
),

2017-01-31 11:44 UTC, KamiNoSierhej commented on src/portal/urls.py
> +from . import views
imports from django 
<empty space>
imports from project

2017-01-31 11:47 UTC, KamiNoSierhej commented on src/portal/templates/portal/index.html
> +    <a href="{% url "logout" %}">Logout</a>
"{% url "logout" %}" >> "{% url 'logout' %}"

^^ Just curious if it suppose to be like that

2017-01-31 11:50 UTC, RadekLejba commented on src/portal/templates/portal/index.html
> +    <a href="{% url "logout" %}">Logout</a>
Acctually it can

2017-01-31 11:52 UTC, RadekLejba commented on src/portal/urls.py
> +    url(r'^login/$',
I am confused how to do it exactly. Based on http://stackoverflow.com/questions/22775697/how-to-specify-long-url-patterns-using-regex-so-that-they-follow-pep8-guidelines.

2017-01-31 11:57 UTC, 8r2y5 commented on src/portal/urls.py
> +    url(r'^login/$',
It is correct - no need to change.

2017-01-31 11:59 UTC, 8r2y5 commented on src/portal/templates/registration/login.html
> +	<a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request }}">Login with Google</a>
Please be consistent. Change `'` to `"`.

2017-01-31 11:59 UTC, 8r2y5 commented on src/portal/tests.py
> +            reverse('home')
What in oblivion is that. Please use `format`.

2017-01-31 12:02 UTC, 8r2y5 commented on src/portal/urls.py
> +        name='login'),
Style.

2017-01-31 12:03 UTC, 8r2y5 commented on src/portal/urls.py
> +    url(r'^logout/$',
Style - indent.

2017-01-31 12:03 UTC, 8r2y5 commented on src/portal/urls.py
> +        name='logout'),
Style - indent.

2017-01-31 12:07 UTC, 8r2y5 commented on src/portal/tests.py
> +class LoginTestCase(TestCase):
Please add unit tests for logout.

2017-01-31 12:34 UTC, KamiNoSierhej commented on src/portal/templates/portal/index.html
> +    <a href="{% url "logout" %}">Logout</a>
ok

2017-01-31 13:34 UTC, RadekLejba commented on src/portal/tests.py
> +class LoginTestCase(TestCase):
Fixed.

2017-01-31 13:48 UTC, wiaterb commented on src/portal/tests.py
> +from django.urls import reverse
sort imports
```
from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse
```

2017-01-31 13:48 UTC, wiaterb commented on src/portal/views.py
> +from django.contrib.auth.decorators import login_required
ditto

2017-01-31 13:50 UTC, wiaterb commented on src/portal/tests.py
> +        index_url = reverse('login')
is it index url or login url? the vavriable name is missleading

2017-01-31 13:50 UTC, wiaterb commented on src/portal/tests.py
> +        response = self.client.get(index_url)
```
response = self.client.get(reverse('login'))
```

2017-02-01 09:12 UTC, 8r2y5 commented
After successful login my url looks like this `http://localhost:8000/portal/?next=%3CWSGIRequest%3A%20GET%20%27/portal/login/%3Fnext%3D/portal/%27%3E`

Here is log:
```
[01/Feb/2017 09:08:10] "GET /portal HTTP/1.1" 301 0
[01/Feb/2017 09:08:10] "GET /portal/ HTTP/1.1" 302 0
[01/Feb/2017 09:08:10] "GET /portal/login/?next=/portal/ HTTP/1.1" 200 1156
[01/Feb/2017 09:08:10] "GET /static/portal/css/bootstrap.min.css HTTP/1.1" 200 150996
[01/Feb/2017 09:08:10] "GET /static/portal/js/jquery-3.1.1.min.js HTTP/1.1" 200 86709
[01/Feb/2017 09:08:10] "GET /static/portal/js/tether.min.js HTTP/1.1" 200 24632
[01/Feb/2017 09:08:10] "GET /static/portal/js/bootstrap.min.js HTTP/1.1" 200 46653
[01/Feb/2017 09:08:12] "GET /portal/login/google-oauth2/?next=%3CWSGIRequest:%20GET%20%27/portal/login/?next=/portal/%27%3E HTTP/1.1" 302 0
[01/Feb/2017 09:08:24] "GET /portal/complete/google-oauth2/?state=wlohTJz9ENDlujhMb3TfwN1MIHMk47t7&code=4/pFSWlBBdB541tp0o05u-Z9k-i8CIADDGHAqd-45zwpY&authuser=0&hd=stxnext.pl&session_state=b841b3e7d89af1279b3db5edb6a93117e51513a7..f1a9&prompt=consent HTTP/1.1" 302 0
[01/Feb/2017 09:08:24] "GET /portal/?next=%3CWSGIRequest%3A%20GET%20%27/portal/login/%3Fnext%3D/portal/%27%3E HTTP/1.1" 200 1114
```

2017-02-02 08:30 UTC, 8r2y5 approved these changes

2017-02-06 08:21 UTC, 8r2y5 requested changes

2017-02-06 08:21 UTC, 8r2y5 commented on src/portal/templates/registration/login.html
> +	<a href="{% url "social:begin" "google-oauth2" %}">Login with Google</a>
Please fix indent.

2017-02-09 08:44 UTC, KamiNoSierhej approved these changes

2017-02-09 09:46 UTC, 8r2y5 approved these changes

2017-02-09 10:44 UTC, merged

2017-02-13 08:59 UTC, lukkolstx commented on setup.py
> +>>>>>>> master
Resolve conflict